"""empty message

Revision ID: 4808097d003c
Revises: 36b93d81ad60
Create Date: 2015-03-04 12:34:52.568530

"""

# revision identifiers, used by Alembic.
revision = '4808097d003c'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Jan', sa.String(), nullable=False),
    sa.Column('Gurecky', sa.String(), nullable=False),
    sa.Column('Muz', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Gurecky', 'loguser', ['Gurecky'], unique=False)
    op.create_table('karty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cislokarty', sa.String(), nullable=False),
    sa.Column('Time', sa.String(), nullable=False),
    sa.Column('WTime', sa.Boolean(name='zena'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_karty'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_karty_Time', 'karty', ['Time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_karty_Time', table_name='karty')
    op.drop_table('karty')
    op.drop_index('ix_loguser_Gurecky', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
